---
- hosts: localhost
  gather_facts: yes
  connection: local 
  vars:
    region: ap-southeast-2
    id: i-034b2b5434a23423s
  tasks:
    - name: start the instance
      ec2:
        region: "{{ region }}"
        instance_ids: "{{ id }}"
        state: running
        wait: yes

